---
- name: add backports packages for debian
  copy:
    src: etc/apt/sources.list.d/backports.list
    dest: /etc/apt/sources.list.d/backports.list
    owner: root
    group: root
    mode: 0644

- name: ensure wireguard packages are installed (only in backports)
  apt:
    pkg: "{{ packages }}"
    state: latest
    default_release: buster-backports
    update_cache: yes
    cache_valid_time: 600
  vars:
    packages:
      - wireguard

- name: ensure qrencode packages are installed
  apt:
    pkg: "{{ packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  vars:
    packages:
      - qrencode
