---
- include: apticron.yml
  tags:
    - apticron
- include: disk-check.yml
  tags:
    - disk
- include: userdot.yml
  tags:
    - user
- include: nftables.yml
  tags:
    - firewall
- include: dnsmasq.yml
  when: need_dns == true
  tags:
    - dns
- include: ntp.yml
- include: tools.yml
- include: misc.yml
