---
- name: ensure dnsmasq packages are installed
  apt:
    pkg: "{{ packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  vars:
    packages:
      - dnsmasq

- name: configure dnsmasq
  template:
    src: etc/dnsmasq.d/local.conf.j2
    dest: /etc/dnsmasq.d/local.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dnsmasq

- name: ensure all dnsmasq services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - dnsmasq
