---
- include: busybox.yml
- include: disable-swap.yml
  tags:
    - swap
- include: userdot.yml
  tags:
    - user
- include: nftables.yml
  tags:
    - firewall
- include: dnsmasq.yml
  when: need_dns == true
  tags:
    - dns
- include: ntp.yml
- include: tools.yml
  tags:
    - tools
- include: misc.yml
