---
- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: restart nftables
  service:
    name: nftables
    state: restarted

- name: restart ntp
  service:
    name: ntp
    state: restarted
