---
- name: ensure postfixadmin support packages are installed
  apt:
    pkg: "{{ packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  vars:
    packages:
      - postfixadmin

- name: disable default apache postfixadmin conf
  command: a2disconf postfixadmin
  notify:
    - reload apache2

- name: configure postfixadmin
  template:
    src: etc/postfixadmin/config.local.php.j2
    dest: /etc/postfixadmin/config.local.php
    owner: root
    group: www-data
    mode: 0640
  tags:
    - postfixadminconf

- name: add symlink to config.local.php
  file:
    path: /usr/share/postfixadmin/config.local.php
    src: /etc/postfixadmin/config.local.php
    state: link

- name: create templates_c and make writeble by web server
  file:
    path: /usr/share/postfixadmin/templates_c
    state: directory
    owner: root
    group: www-data
    mode: 0770

- name: create database for mail server
  mysql_db:
    name: postfix
    state: present
    login_password: "{{ db_root_passwd }}"
    login_user: root
  when: db_root_passwd != ""

- name: create mysql read only user for mail database
  mysql_user:
    name: postfix
    host: localhost
    password: "{{ postfix_db_passwd }}"
    priv: postfix.*:SELECT
    state: present
    login_password: "{{ db_root_passwd }}"
    login_user: root
  when: postfix_db_passwd != "" and db_root_passwd != ""

- name: create mysql admin user for mail database
  mysql_user:
    name: postfixadmin
    host: localhost
    password: "{{ postfix_admin_db_passwd }}"
    priv: postfix.*:ALL
    state: present
    login_password: "{{ db_root_passwd }}"
    login_user: root
  when: postfix_admin_db_passwd != "" and db_root_passwd != ""

- name: add mail vhosts to apache
  template:
    src: etc/apache2/sites-available/{{ item }}.j2
    dest: /etc/apache2/sites-available/{{ item }}
    owner: root
    group: root
    mode: 0640
  with_items:
    - mail.conf
  notify:
    - reload apache2
  when: postfix_admin_db_passwd != ""
